### PR TITLE
Vignette 

### PR DESCRIPTION
**Pull request by benjaminhlina**
I have added a comprehensive vignette with both the Ramsey Horseshoe example and an example lake that has a few islands and is a bit more complex. I have also changed the README, which depending on how you feel can be left or amended.  Considering I moved Ramsey Horseshoe example to the vignette I suggested/pointed users to use the vignette, but if we want a simple example on the readme to give the user an general idea then that makes total sense too!

Cheers,
Ben

### CODE REVIEW

**Comment by dill** [comment]
Thanks for this @benjaminhlina! Again, these look like excellent additions, especially the inclusion of a more detailed example.

If I can make one suggestion, if you can move that worked example into a `vignettes/` folder, that will allow it to be found more easily by users within R (it gets listed in the help index etc). More details on this are here: https://r-pkgs.org/vignettes.html

Apologies for the tardy reply and laziness on my part, I really appreciate your efforts!

**Comment by dill** [comment]
I'll merge this anyway, as there are obviously some great additions here and the vignette is just a minor cosmetic thing! :)

**Comment by dill** [comment]
whoops, sorry, ignore that question about vignettes, I just noticed it was already there!

**Comment by benjaminhlina** [comment]
Of course happy to have helped get this up and going! Phew, I'm glad the vignette is in the right place. I've never added a vignette to a package before, so it was a bit of figuring out the right steps to get it into the right place. The resource you posted, I went through and found it super helpful! Thanks!

**Pull request merged**
